openapi: 3.1.0
info:
    version: 1.0.0
    title: Книга контактів
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
    description: |
        Книга контактів — це зручний інструмент для збереження та управління вашими контактами.
        Платформа підтримує різноманітні операції, включаючи створення, оновлення, отримання та видалення контактів.
tags:
    - name: Contacts
      description: Операції, пов'язані з контактами
servers:
    - url: http://localhost:3000
      description: Локальний сервер
    - url: https://contacts-app-8puk.onrender.com
      description: Продакшн-сервер
paths:
    /contacts:
        get:
            $ref: "../swagger/paths/contacts/get.yaml"
        post:
            $ref: "../swagger/paths/contacts/post.yaml"
    /contacts/{contactId}:
        get:
            $ref: "../swagger/paths/contacts/{id}/get.yaml"
        patch:
            $ref: "../swagger/paths/contacts/{id}/patch.yaml"
        delete:
            $ref: "../swagger/paths/contacts/{id}/delete.yaml"
components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
